version: '3.8'
services:
  db:
    image: postgres:16
    container_name: estoque_teste_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      retries: 5
      start_period: 40s
      timeout: 10s

  app:
    build: 
      context: ./ms-estoque
    container_name: spring_teste_estoque
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
